### ISSUE TITLE
Portrait images support

### ISSUE THREAD

**Issue by NaturalBornCamper** [stijnvc/subtle-slideshow.js#3]
Is there portrait images support where it would just not stretch? Right now vertical images either appear squeezed, or fill the screen so the top and bottom are missing. Is there a way to have black bars on the sides?

**Comment by NaturalBornCamper** [comment]
Nevermind!

I'm a backend developer, not very good in css but I managed, if other people have the same issue, I changed the `slide` class:

```
#slideshow .slide span {
    /* CHANGES BELOW */
    background-size: contain;
    background-repeat: no-repeat;
    background-color: black;
    /* CHANGES ABOVE */
    /*background-size: cover;*/
    background-position: center;
}
```

**Comment by stijnvc** [comment]
The slideshow is fixed to the size of the `#slideshow` element.
